name: release-test

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v4
      - name: release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export TAG=`date +"%Y%m%d-%H%M%S"`
          export RELEASE_FILE = release-$TAG.zip
          zip ${RELEASE_FILE} -r ./zip
          echo $TAGzip 
          gh --version
          gh release create ${TAG} ${RELEASE_FILE}